export const searchRankingTuning = {
  lexical: {
    exactMatchPoints: {
      specific: 1200,
      broadSingleToken: 720,
    },
    startsWithPoints: {
      specific: 800,
      broadSingleToken: 540,
    },
    includesPoints: {
      specific: 350,
      broadSingleToken: 300,
    },
    fullTokenCoverageBonus: 320,
    coverageScale: 220,
    extraTokenPenalty: {
      specificPerToken: 44,
      broadPerToken: 16,
      maxTokens: 10,
    },
    specificLowCoveragePenalty: 240,
    editionSuffixPenalty: 90,
    nonEditionBonus: 40,
  },
  noisePenalties: {
    base: [
      { keyword: "demo", points: -260 },
      { keyword: "mod", points: -220 },
      { keyword: "fan", points: -180 },
      { keyword: "test", points: -140 },
      { keyword: "prototype", points: -200 },
    ],
    franchise: [
      { keyword: "alpha", points: -260 },
      { keyword: "beta", points: -220 },
      { keyword: "simulator", points: -280 },
      { keyword: "demake", points: -260 },
      { keyword: "fangame", points: -240 },
      { keyword: "free roam", points: -180 },
      { keyword: "soft", points: -220 },
      { keyword: "android", points: -180 },
    ],
  },
  lexicalConfidence: {
    highCoverage: 0.66,
    mediumCoverage: 0.5,
  },
  platformRelevance: {
    missingPlatformPenalty: {
      specific: 40,
      broad: 10,
    },
    webIntentTokens: ["web", "browser", "html5", "io"] as const,
    webIntentPenalty: {
      specific: 40,
      broad: 10,
    },
    webOnlyPenalty: {
      specific: 520,
      broad: 220,
    },
    mainstreamPlatformBonus: 60,
  },
  numericIntent: {
    missingRequestedNumberPenalty: 460,
    otherNumberPenalty: 120,
    exactNumberBonus: 180,
  },
  metadataQuality: {
    releaseDateBonus: {
      specific: 80,
      broad: 20,
    },
    missingReleaseDatePenalty: {
      specific: 220,
      broad: 50,
    },
    missingPlatformPenalty: {
      specific: 140,
      broad: 30,
    },
    singlePlatformPenalty: {
      specific: 60,
      broad: 10,
    },
    platformCountBonusPerPlatform: 28,
    platformCountBonusCap: 112,
    hasCoverImageBonus: 12,
    missingCoverImagePenalty: 24,
  },
  singleTokenFranchise: {
    brandedPrefixBonus: 260,
    highQualityThreshold: 0.55,
    highQualityScale: 220,
    lowQualityThreshold: 0.18,
    lowQualityPenalty: 180,
    weakExactQualityThreshold: 0.45,
    weakExactPenalty: 260,
    parentheticalPenalty: 120,
  },
  specific: {
    denoiseStrongCoverageThreshold: 0.66,
    denoiseStrongScoreThreshold: 720,
    denoisePageOneStrongMin: 6,
    denoiseLaterPagesStrongRatio: 0.2,
    denoiseLaterPagesStrongMinFloor: 2,
    derivativeTopWindow: 5,
    derivativeTopCap: 1,
    derivativeCoverageThreshold: 0.66,
    derivativeBaseTokenMin: 2,
    derivativeDemoteBasePenalty: 220,
    derivativeDemoteExtraTokenThreshold: 4,
    derivativeDemoteExtraPenalty: 60,
    derivativeQualityProtectedThreshold: 0.58,
    derivativeMainstreamSolidQualityThreshold: 0.45,
    derivativeStrongPopularityRatingsCount: 4000,
    derivativeStrongPopularityAdded: 12000,
    sequelCoverageThreshold: 0.66,
    sequelBoost: 120,
  },
  broad: {
    lowSignal: {
      exactQualityThreshold: 0.18,
      exactWebPenalty: 720,
      exactPenalty: 560,
      exactWebMidQualityThreshold: 0.5,
      exactWebMidQualityPenalty: 620,
      startsWithQualityThreshold: 0.12,
      startsWithWebPenalty: 320,
      startsWithPenalty: 180,
    },
    recency: {
      lexicalAnchorCoverageStrong: 0.72,
      lexicalAnchorCoverageMedium: 0.5,
      lowQualityWithoutMainstreamThreshold: 0.2,
      oneDayMs: 24 * 60 * 60 * 1000,
      nearFutureYears: 3,
      nearFutureMainstreamBonus: 180,
      nearFutureOtherBonus: 90,
      farFutureMainstreamBonus: 130,
      farFutureOtherBonus: 65,
      recentPastYears: 2,
      recentPastBonus: 120,
      mediumPastYears: 5,
      mediumPastBonus: 70,
      olderPastYears: 10,
      olderPastBonus: 35,
    },
    denoise: {
      lowQualityThreshold: 0.16,
      veryLowEngagementRatingsCount: 50,
      veryLowEngagementAdded: 250,
      veryLowEngagementReviewsCount: 25,
      minimumRetainedCap: 3,
    },
  },
  anticipationProtection: {
    strongPopularityAdded: 8000,
    strongPopularityRatingsCount: 1500,
    majorQualityMetacritic: 80,
    majorQualityRating: 4.2,
    majorEngagementRatingsCount: 1200,
    majorEngagementAdded: 7000,
    recentMajorYears: 8,
  },
} as const;
